# Generated by Django 5.1.2 on 2024-12-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ServicioConsultoria',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.PositiveIntegerField(default=0, help_text='Duración en horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
