# Generated by Django 5.1.2 on 2024-12-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0003_remove_capacitacion_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_creacion',
        ),
    ]
