# Generated by Django 5.1.2 on 2024-12-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0004_delete_curso_remove_capacitacion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(upload_to='services/')),
                ('image_2', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.DeleteModel(
            name='Capacitacion',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
