# Generated by Django 5.1.2 on 2024-12-26 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0005_service_delete_capacitacion_delete_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_categories/', verbose_name='Ícono')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden de Presentación')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Servicio Activo'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden de Presentación'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Descripción del Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título del Servicio'),
        ),
        migrations.CreateModel(
            name='ServiceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Subcategoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden de Presentación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='consultoria.servicecategory', verbose_name='Categoría Principal')),
            ],
            options={
                'verbose_name': 'Subcategoría de Servicio',
                'verbose_name_plural': 'Subcategorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='consultoria.servicesubcategory', verbose_name='Subcategoría'),
        ),
    ]
