# Generated by Django 5.1.2 on 2024-12-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0006_servicecategory_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/', verbose_name='Imagen 1'),
        ),
    ]
