# Generated by Django 5.1.2 on 2024-12-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0007_remove_servicecategory_icon_servicecategory_image_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='image_1',
            new_name='image',
        ),
    ]
