# Generated by Django 5.1.2 on 2025-01-03 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0008_rename_image_1_servicecategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Brochure')),
                ('file', models.FileField(help_text='Subir archivo en formato PDF', upload_to='brochures/', verbose_name='Archivo PDF')),
            ],
            options={
                'verbose_name': 'Brochure',
                'verbose_name_plural': 'Brochures',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Noticia')),
                ('slug', models.SlugField(help_text='URL única para la noticia', max_length=255, unique=True, verbose_name='URL amigable')),
                ('image', models.ImageField(help_text='Imagen principal de la noticia', upload_to='news/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Contenido')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-publication_date'],
            },
        ),
    ]
