# Generated by Django 5.1.2 on 2025-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0009_brochure_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Oferta')),
                ('description', models.TextField(verbose_name='Descripción de la Oferta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de la Oferta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Imagen de la Oferta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Oferta Activa')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
